### ISSUE TITLE
Server Error in '/Shopline' Application.  Index and length must refer to a location within the string. Parameter name: length

### ISSUE THREAD

**Issue by mozgbrasil** [dilneiss/itaubankline#1]
Ola Boa Tarde meu amigo

-

Isolei o seguinte programa que deve enviar informações ao itaushopline para o processamento de transação

https://mozg-1224.appspot.com/?action=transaction_itau

Veja que já está preenchido os parametros codEmp e Chave

Ao clicar em enviar é exibido a tela de erro do itaushopline

Mas como não houve tratamento por parte do itau para expor o motivo do erro, fica impossível interpretar o motivo da ocorrência

Sabe informar o motivo da ocorrência ?

-

Você pode fazer uma outra simulação 

Acesse

https://mozg-1224.appspot.com/?action=transaction_itau

altere no campo pedido para 13 por exemplo, mas pode ser qualquer coisa

Verá que é exibido a tela do itau shopline solicitando escolher as modalidades que o itau oferece como Boleto ou Debito Bancario

Clique em Boleto e em seguida em Imprimir

Verá que é exibido o erro 

Server Error in '/Shopline' Application.  Index and length must refer to a location within the string. Parameter name: length

-

Peguei esses dados codEmp e Chave expostos em 

https://github.com/.../9cec4026d86f08da.../_scripts/ajax.php

-

**Comment by mozgbrasil** [comment]
Esse erro foi ocasionado pois eu estava postando 

'dataVencimento' => '28062056',

**Comment by dilneiss** [comment]
Opa boa noite

Então deu certo agora?

Att.
Dilnei

2016-12-19 15:03 GMT-02:00 mozgbrasil <notifications@github.com>:

**Comment by mozgbrasil** [comment]
Ola Bom dia

Funcionando

Obrigado pela atenção
