### ISSUE TITLE
Sobre descriptograr

### ISSUE THREAD

**Issue by mozgbrasil** [dilneiss/itaubankline#2]
Ola Boa Tarde meu amigo

Gostaria de saber se é possível descriptografar os dados criptografados

$dados_criptografados = $itauCripto->geraDados(...

**Comment by dilneiss** [comment]
Opa boa noite

Não tem como amigo.. Ao menos não descobri uma forma ainda, mas pra que
você quer isso?

Att.
Dilnei

2016-12-19 17:04 GMT-02:00 mozgbrasil <notifications@github.com>:

**Comment by mozgbrasil** [comment]
Ola Bom dia

Somente uma curiosidade de possibilidades, vi um método chamado decripto( pensei nessa possibilidade para eventual possibilidades

**Comment by mozgbrasil** [comment]
Fechando
